language: node_js
node_js:
  - node
script:
  -
deploy:
  provider: firebase
  token:
    secure: oJV8c0xZhUfAZ0ChZqkthx6cLt9Mrd4rB+6B3ucuVprNOc56TLWONfdnsWDRfPgmVAezahwQR0KPTUoWFDCaZKnibhcbUDXmKrp3X5CY3OQePyU4WOkyPrGvdTo5jJt7YktMVOHwxqKUndMylJo4e81SOry1h5l0Rsj3wuLhikfT3z4HPnAutRzH3Snf9jiirj3JJGW/gLyAunRJHwm91PQN2WAgZj/JOmkbNFelTUTDmqOnWifEGsvGx9Wv3JtjLDqewe4C5DUB4WrJgaR7N+IC96aLFrJUuE0SHbY5N0PYFT0hka7wKG1Z+N4+nLJfj4EifZHWBXfPP/5U/Fk5Tn3EylHtL3e7ZJ+RuADOHOQheQmFTxVEgkmwmp2/TcVsV7+kBdXmJc/ElCO9RiOCf1wa5SOBLdf2HdOsAgE1afXf4O3NpcY7H3owUMjGSo+TEaTgRUruekot6FRoXdgjnGVAc/nSE6sX4bYtpjI0QFSovQufhoEV+N4htUyqlHNxlG4xyLao7nJvoPN+jLkQsrntRMORPHkfs+wSadiQZGCK0XSXN85FAhyccOf52spq95Tw+xoVwXCADc30b7GXJCuET0n1W/J6ab0i8YzipPIpkomHFxoZBrcUQOrIJ4olQy3HLvzcRed8V7ttoMfsFvL+GeBPDPXZTWlcfJNh7Dw=
