language: node_js
node_js:
  - node
script:
  -
deploy:
  provider: firebase
  token:
    secure: cVYhisgow+cStQq1hszrUAWB3/LGgBzQ7U6M2ppY7QBozED23P6CCRjdg7Gj7jwH+KsuVXc1xzmM8x69UfTuZoB69PyYls6ou3dcyIkGgtffBv0hKEBwB80IN8LDsnpzwjVM4l9KWGfT0Q5GipvFUdf6zZKCSIZh62+ZXq4TtBWWBlN/Bv8nreoYHVYF8ruFOps6URXO8gwzkwDt5cipgC7Y2j6g7UL/WyULGb/TEZ3ebphmMcIAjQxf9zUO8IsQYNOuelHKmSWr24STlygXDBzkrXyU54ztRLnmV0rQyBOBL5lZdpEz/Pp+08zVuleoyo1Huflfa0W2+idorvRqwUYhU+opd5LK1kG2X9wm/Wyiry2Yq5jmrCxKFrOAtJ4uoxqwvMghAYCyXfz2fKsVo1JiPdBeuI1mUovMJIiJ+YB+hP02Mm4gDvx40gyy5vumutZ0whaHAb8oes0RbdPmu4RYdr/N+McpCWo6elZrcEj0NJL4/wcTJwt/jr5oH6FAMOGPM9GMKa5IE4zljaRGoxBvTcHanPPpZSipMhRVXJua59fj5C14i3r5HrgYRypr9SomxK05wzqxrQ787GEgsI2MXCw+3bl7jOC3zT6e3Lh0Mv65k3pozNWm2XMU79BXHmjJG0CL83zCK4yQMTUkpEPZpOeG66AYVtO/VmmhHdg=
