name: Build and Deploy
on:
  push:
    branches:
    - main

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2
      - name: Firebase GitHub Action
        uses: pizzafox/firebase-action@1.0.7
        env:
          PROJECT_ID: "tigerjelly-com-51229"
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        with:
          args: deploy
